# Generated by Django 5.2.17 on 2026-10-06 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My SpaceFruit Garden', max_length=100)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('community', 'Community')], default='private', max_length=12)),
                ('location_label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_gardens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('location_label', models.CharField(blank=True, max_length=120)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spacefruit_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GardenMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='spacefruit_api.garden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('garden', 'user'), name='unique_garden_member')],
            },
        ),
        migrations.CreateModel(
            name='GardenPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=24)),
                ('plant_type', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('planted', 'Planted'), ('harvested', 'Harvested')], default='empty', max_length=12)),
                ('health_status', models.CharField(blank=True, max_length=100)),
                ('health_issues', models.JSONField(blank=True, default=list)),
                ('planted_at', models.DateTimeField(blank=True, null=True)),
                ('last_monitored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='spacefruit_api.garden')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('garden', 'label'), name='unique_plot_label_per_garden')],
            },
        ),
        migrations.CreateModel(
            name='HarvestInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(max_length=80)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('image_path', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_inventory', to='spacefruit_api.garden')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('garden', 'plant_type'), name='unique_harvest_type_per_garden')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('trade', 'Trade'), ('buy', 'Buy / Sell'), ('donate', 'Donate')], max_length=8)),
                ('plant_type', models.CharField(max_length=80)),
                ('quantity', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_unit', models.CharField(default='lb', max_length=4)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image_path', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='spacefruit_api.garden')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['section', 'active', 'created_at'], name='spacefruit__section_ba1a2d_idx')],
            },
        ),
    ]
